apiVersion: apps/v1
kind: Deployment
metadata:
  name: lxp-admin
  namespace: lxp
  labels:
    app: lxp-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lxp-admin
  template:
    metadata:
      labels:
        app: lxp-admin
    spec:
      containers:
        - name: lxp-admin
          image: lxp-admin:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_USERNAME
              value: default
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infra-secret
                  key: redis-password

          # 기본적으로 스프링 환경은 메모리 잡아먹는 양이 있으므로, 메모리를 너무 낮추면 안됨
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: lxp-admin
  namespace: lxp
spec:
  type: NodePort
  selector:
    app: lxp-admin
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30086