apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lxp-ingress
  namespace: lxp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: api.lxp.local
      http:
        paths:
          - path: /recommend(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: lxp-recommend
                port:
                  number: 8080
          - path: /content(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: lxp-content
                port:
                  number: 8080
