apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lxp-ingress
  namespace: lxp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: content.lxp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lxp-content
                port:
                  number: 8080
