# lxp-user Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lxp-user
  namespace: lxp
  labels:
    app: lxp-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lxp-user
  template:
    metadata:
      labels:
        app: lxp-user
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: lxp-user
          image: minyong96/lxp:lxp-user-latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 5
          ports:
            - containerPort: 8080
          env:
            - name: PASSPORT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lxp-passport-secret
                  key: PASSPORT_SECRET
            - name: INTERNAL_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lxp-auth-internal
                  key: INTERNAL_AUTH_TOKEN
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT
              value: "-1"
            - name: JAVA_TOOL_OPTIONS
              value: >
                -Xms512m
                -Xmx1024m
                -XX:MaxMetaspaceSize=256m
                -XX:+UseG1GC
                -XX:MaxGCPauseMillis=200

            # MySQL (공용)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://lxp-mysql:3306/lxp_user_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lxp-mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lxp-mysql-secret
                  key: password
            # RabbitMQ
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: infra-secret
                  key: rabbitmq-username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infra-secret
                  key: rabbitmq-password
            # Redis
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_USERNAME
              value: default
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infra-secret
                  key: redis-password
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "2Gi"
          cpu: "1000m"


---
apiVersion: v1
kind: Service
metadata:
  name: lxp-user
  namespace: lxp
spec:
  type: NodePort
  selector:
    app: lxp-user
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081